version: "3.9"
services:
  go:
    build:
      context: ./api
      dockerfile: ../.docker/go/Dockerfile
    container_name: goorm_api
    ports:
      - 13000:3000
    depends_on:
      - db
    volumes:
      - ./api:/app
    env_file:
      - .docker/go/.env
    restart: always

  adminer:
    image: adminer
    restart: always
    container_name: goorm_adminer
    depends_on:
      - db
    ports:
      - 18080:8080
    environment:
      # @see https://github.com/vrana/adminer/tree/master/plugins
      - ADMINER_PLUGINS=enum-types edit-textarea enum-option json-column

  db:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    container_name: goorm_db
    ports:
      - 15432:5432
    env_file:
      - .docker/postgres/.env
    restart: always
